# Generated by Django 3.0.3 on 2021-04-14 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('datetime_ordered', models.DateTimeField(auto_now_add=True)),
                ('order_completed', models.BooleanField(default=False)),
                ('unique_code', models.CharField(blank=True, max_length=4, unique=True)),
                ('address', models.CharField(choices=[('Home', 'Home'), ('Hostel', 'Hostel'), ('Health Center', 'Health center'), ('Chapel', 'Chapel'), ('Cafeteria', 'Cafeteria'), ('Old College', 'Old College'), ('New College', 'New College'), ('Library', 'Library')], max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=1000, null=True)),
                ('category', models.CharField(choices=[('FD', 'Food'), ('SH', 'Shirt'), ('SHS', 'Shoes'), ('MN', 'Men'), ('WM', 'Women'), ('FH', 'Fashion'), ('TR', 'Trouser'), ('ACC', 'Accesories'), ('ACA', 'Academics')], default='shoes', max_length=5)),
                ('tag', models.ManyToManyField(to='shop.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('datetime_ordered', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
    ]
