# Generated by Django 3.0.3 on 2021-04-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210414_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Cleared', 'Cleared'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
