# Generated by Django 3.0.3 on 2021-04-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210416_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
