# Generated by Django 3.0.3 on 2021-04-20 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_auto_20210420_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.IntegerField(default=0, null=True)),
                ('hall', models.CharField(choices=[('ABG', 'Abigail'), ('ABM', 'Abraham'), ('DNL', 'Daniel'), ('DBH', 'Deborah'), ('DOR', 'Dorcas'), ('JSP', 'Joseph'), ('ISC', 'Isaac'), ('SRH', 'Sarah')], max_length=500, null=True)),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500')], max_length=500, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
