# Generated by Django 3.0.3 on 2021-04-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reg_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
