# Generated by Django 3.0.3 on 2021-04-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210421_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Cleared', 'Cleared'), ('Delivered', 'Delivered')], default='Pending', max_length=200, null=True),
        ),
    ]
