# Generated by Django 3.0.3 on 2021-04-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210426_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(choices=[('Home', 'Home'), ('Hostel', 'Hostel'), ('Health Center', 'Health center'), ('Chapel', 'Chapel'), ('Cafeteria', 'Cafeteria'), ('Old College', 'Old College'), ('New College', 'New College'), ('Library', 'Library')], default='Hostel', max_length=200),
        ),
    ]
