# Generated by Django 3.0.3 on 2021-05-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210428_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
