# Generated by Django 3.0.3 on 2021-05-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20210506_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='unique_code',
            new_name='order_code',
        ),
    ]
